class AppImages {
  AppImages._();
  static const waiting = "assets/images/waiting.png";
  static const porkin = "assets/images/porkin.png";
  static const google = "assets/images/google.png";
  static const microsoft = "assets/images/microsoft.png";
  static const appliances = "assets/images/appliances.png";
  static const baby = "assets/images/baby.png";
  static const car = "assets/images/car.png";
  static const clothing = "assets/images/clothing.png";
  static const entertainment = "assets/images/entertainment.png";
  static const food = "assets/images/food.png";
  static const fuel = "assets/images/fuel.png";
  static const gift = "assets/images/gift.png";
  static const gym = "assets/images/gym.png";
  static const hobby = "assets/images/hobby.png";
  static const hospital = "assets/images/hospital.png";
  static const house = "assets/images/house.png";
  static const pending = "assets/images/pending.png";
  static const pharmacy = "assets/images/pharmacy.png";
  static const repairs = "assets/images/repairs.png";
  static const savings = "assets/images/savings.png";
  static const security = "assets/images/security.png";
  static const shopping = "assets/images/shopping.png";
  static const streaming = "assets/images/streaming.png";
  static const tax = "assets/images/tax.png";
  static const transaction = "assets/images/transaction.png";
  static const transport = "assets/images/transport.png";
  static const travel = "assets/images/travel.png";
  static const wallet = "assets/images/wallet.png";
  static const withdraw = "assets/images/withdraw.png";
  }
